### ISSUE TITLE
Should not assume users table id is called `id`

### ISSUE THREAD

**Issue by erikdonohoo** [hmshafeeq/userstamps#1]
The code should determine the model class being used for users and use the `$primaryKey` property.  We don't have an `id` column for our users table, and have it modified using the `$primaryKey` property.  The code here should read from that.

**Comment by hmshafeeq** [comment]
@erikdonohoo Thanks for the suggestion. I have fixed this, get the latest version with a composer update and let me know if it serves your requirement.

**Comment by hmshafeeq** [comment]
I have included the fix for this issue in v0.1.2.
